/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package victorito_halleyy;

/**
 *
 * @author Martin
 */
public class Agregar_Clientee extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Clientee
     */
    public Agregar_Clientee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LB1 = new javax.swing.JLabel();
        L_IMAGE = new javax.swing.JLabel();
        LB2 = new javax.swing.JLabel();
        LB3 = new javax.swing.JLabel();
        LB7 = new javax.swing.JLabel();
        LB5 = new javax.swing.JLabel();
        LB4 = new javax.swing.JLabel();
        LB6 = new javax.swing.JLabel();
        BTN2 = new javax.swing.JButton();
        BTN3 = new javax.swing.JButton();
        TXTF5 = new javax.swing.JTextField();
        SP5 = new javax.swing.JSeparator();
        TXTF3 = new javax.swing.JTextField();
        SP3 = new javax.swing.JSeparator();
        TXTF4 = new javax.swing.JTextField();
        SP4 = new javax.swing.JSeparator();
        TXTF2 = new javax.swing.JTextField();
        SP2 = new javax.swing.JSeparator();
        TXTF1 = new javax.swing.JTextField();
        SP1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LB1.setForeground(new java.awt.Color(214, 0, 110));
        LB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB1.setText("Agregar Cliente");
        jPanel1.add(LB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 80));

        L_IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colores.jpg"))); // NOI18N
        jPanel1.add(L_IMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 80));

        LB2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LB2.setText("Nombre del Cliente:");
        jPanel1.add(LB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 101, -1, -1));

        LB3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LB3.setText("Empresa:");
        jPanel1.add(LB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 132, -1, -1));

        LB7.setText("En los campos E-Mail y telefono es obligatorio llenar alguno de los dos ");
        jPanel1.add(LB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 173, 380, -1));

        LB5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LB5.setText("Telefono:");
        jPanel1.add(LB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 210, -1, -1));

        LB4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LB4.setText("E-mail:");
        jPanel1.add(LB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 252, -1, -1));

        LB6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LB6.setText("RFC(Opcional):");
        jPanel1.add(LB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 317, -1, -1));

        BTN2.setBackground(new java.awt.Color(0, 193, 193));
        BTN2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BTN2.setText("Subir Registro");
        BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(BTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 369, -1, -1));

        BTN3.setBackground(new java.awt.Color(0, 193, 193));
        BTN3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BTN3.setText("Limpiar todos los Campos");
        BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN3ActionPerformed(evt);
            }
        });
        jPanel1.add(BTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 369, -1, -1));

        TXTF5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTF5.setBorder(null);
        TXTF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTF5ActionPerformed(evt);
            }
        });
        jPanel1.add(TXTF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 317, 324, 20));

        SP5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 337, 324, 10));

        TXTF3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTF3.setBorder(null);
        jPanel1.add(TXTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 242, 325, 30));

        SP3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 272, 325, 10));

        TXTF4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTF4.setBorder(null);
        TXTF4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTF4KeyTyped(evt);
            }
        });
        jPanel1.add(TXTF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 20));

        SP4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, 10));

        TXTF2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTF2.setBorder(null);
        jPanel1.add(TXTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 116, 325, 30));

        SP2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 149, 325, 12));

        TXTF1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTF1.setBorder(null);
        TXTF1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTF1.setDoubleBuffered(true);
        TXTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTF1ActionPerformed(evt);
            }
        });
        TXTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTF1KeyTyped(evt);
            }
        });
        jPanel1.add(TXTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 325, 30));

        SP1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 114, 325, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN2ActionPerformed

    private void BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN3ActionPerformed

    }//GEN-LAST:event_BTN3ActionPerformed

    private void TXTF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTF5ActionPerformed

    private void TXTF4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTF4KeyTyped
        char n = evt.getKeyChar();
        if(( n<  '0' || n> '9')) evt.consume();
    }//GEN-LAST:event_TXTF4KeyTyped

    private void TXTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTF1ActionPerformed

    private void TXTF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTF1KeyTyped
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_TXTF1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Clientee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Clientee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Clientee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Clientee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Clientee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN2;
    private javax.swing.JButton BTN3;
    private javax.swing.JLabel LB1;
    private javax.swing.JLabel LB2;
    private javax.swing.JLabel LB3;
    private javax.swing.JLabel LB4;
    private javax.swing.JLabel LB5;
    private javax.swing.JLabel LB6;
    private javax.swing.JLabel LB7;
    private javax.swing.JLabel L_IMAGE;
    private javax.swing.JSeparator SP1;
    private javax.swing.JSeparator SP2;
    private javax.swing.JSeparator SP3;
    private javax.swing.JSeparator SP4;
    private javax.swing.JSeparator SP5;
    private javax.swing.JTextField TXTF1;
    private javax.swing.JTextField TXTF2;
    private javax.swing.JTextField TXTF3;
    private javax.swing.JTextField TXTF4;
    private javax.swing.JTextField TXTF5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
